### ISSUE TITLE
Addition of abortOn in the guide code would have no effect

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/iguide-retry-timeout#139]
`retryOn` is used to indicate which exceptions should trigger a retry

`abortOn` is used to identify a subset of the exceptions included in `retryOn` which should **not** be retried

The key here is that adding an exception to `abortOn` only makes sense if a superclass of the exception is listed in `retryOn`. If this is not the case then adding it to `abortOn` won't have any effect since it wouldn't have been retried anyway.

Given this, the example in guide which has
```
@Retry(retryOn = TimeoutException.class,
       abortOn = FileNotFoundException.class)
```
doesn't make sense since `FileNotFoundException` does not extend `TimeoutException`.

In other respects, the explanation of `abortOn` in the guide is good. It's just the code in the specific scenario that doesn't make sense.

**Comment by dmorgant** [comment]
Silly us!

Ok....I've extended the example in both the guide and in the sample application to include `IOException` in the `retryOn` parameter.  `FileNotFoundException` is a subclass of `IOException` so now the rest of the write up makes sense since the Retry Policy will retry on `IOExceptions`, except when it is a `FileNotFoundException`.   In the sample application we force a `FileNotFoundException` to be thrown via the setting of a flag in the code to demonstrate what will occur.
