### ISSUE TITLE
First time introduction of progress bar can be confusing

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguide-retry-timeout#93]
**Objective**:

- [ ] When we first introduce the animated timeline, readers might wonder what the red and green tick marks represent.  Eventually, the user can figure it out by reading the text in the green instruction.  To avoid confusing, we should consider moving the `Enter` button more towards the end of the instruction so first time readers will read the explanation on the timeline.  The current way we have it, first time readers will be encouraged to hit the `Enter` button.  The `Enter` button greys out the rest of the text explaining the timeline and the eye is immediately drawn to the red/green timeline ticks.

![image.png](https://images.zenhubusercontent.com/59d7b56bb0222d5de47a9368/b273712e-e8e0-4f02-b975-4c395a0632e4)

- [x] Also the playground step is the only place where we label the process bar with `Timeout` and `Retry`.  We should label the first introduction of the progress bar at the least.  **REGRESSION**

**Step:**

https://openlibertydev.mybluemix.net/guides/retry-timeout.html#adding-retry-limits

**Comment by dmorgant** [comment]
The 'Timeout` and `Retry` labels not appearing on ALL timelines is a regression.  I ran a quick test with the above link and we have the following console errors:

VM143:9 GET https://openlibertydev.mybluemix.net/guides/iguides-common/js/interactive-guides/externalized-string.js net::ERR_ABORTED

VM141 retry-timeout.html:1 Refused to execute script from 'https://openlibertydev.mybluemix.net/guides/iguides-common/js/interactive-guides/externalized-string.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by kinueng** [comment]
Hm...
I think the root cause is needing to sync `iguides-common`'s `master` and `dev` branch.

**Comment by kinueng** [comment]
Created https://github.com/OpenLiberty/iguides-common/pull/152 in `iguides-common`

**Comment by kinueng** [comment]
Missing labels `Timeout` and `Retry` has been fixed with OpenLiberty/iguides-common#152

**Comment by kinueng** [comment]
Now that the labels are fixed on the progress bar, the confusion is no longer there.
